# Generated by Django 4.2 on 2023-05-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yotodo', '0003_alter_todoit_description_alter_todoit_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-05-05 05:42'),
            preserve_default=False,
        ),
    ]
