# Generated by Django 4.2 on 2023-05-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yotodo', '0004_todoit_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoit',
            name='lvl',
            field=models.CharField(default=1, max_length=40, verbose_name='Уровень'),
            preserve_default=False,
        ),
    ]
