# Generated by Django 4.2 on 2023-05-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yotodo', '0005_todoit_lvl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoit',
            name='lvl',
            field=models.IntegerField(verbose_name='Уровень'),
        ),
    ]
