# Generated by Django 4.2 on 2023-05-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yotodo', '0008_alter_todoit_isfixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoit',
            name='title',
            field=models.CharField(max_length=35, verbose_name='Задача'),
        ),
    ]
