# Generated by Django 4.2 on 2023-05-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yotodo', '0002_alter_todoit_options_alter_todoit_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoit',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='todoit',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='todoit',
            name='user',
            field=models.IntegerField(),
        ),
    ]
