# Generated by Django 4.2 on 2023-05-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yotodo', '0007_todoit_isfixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoit',
            name='isfixed',
            field=models.IntegerField(),
        ),
    ]
