# Generated by Django 4.2 on 2023-05-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yotodo', '0009_alter_todoit_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoit',
            name='title',
            field=models.CharField(max_length=32, verbose_name='Задача'),
        ),
    ]
