# Generated by Django 4.2 on 2023-05-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yotodo', '0010_alter_todoit_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoit',
            name='isfixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todoit',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Задача'),
        ),
    ]
