# Generated by Django 4.2 on 2023-06-17 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yotodo', '0012_todoit_end_at_alter_todoit_isfixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
